import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "../components";
import StoreProvider from './StoreProvider';
import { ThemeButton } from "@/components/NavItem";
import { themeStyles } from "./globalStyle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
            </head>
            <body className={`${inter.className} ${themeStyles.primaryBackground}`} suppressHydrationWarning={true}>
                <StoreProvider>
                    <Header>
                        <ThemeButton/>
                    </Header>
                    {children}
                    <Footer />
                </StoreProvider>
            </body>
        </html>
    );
}
